### ISSUE TITLE
Trying to use apt, not working

### ISSUE THREAD

**Issue by kakila** [gnu-octave/docker#1]
If I understood the image hierarchy correctly, when using gnuoctave/octave:6.2.0 one should have an Ubuntu 20.04 (focal) environment.

I tried to use apt and apt-get but they seem to be pulling from bionic repositories. See the output of the job:

https://gitlab.com/kakila/elementary_effects/-/jobs/1082211728

also, apt commands to manage sources.list did not work.

**Comment by siko1056** [comment]
Greetings @kakila :wave: 

You were too fast, sorry.  I updated the builds to Ubuntu 20.04 two days ago 8d3decb8cb8515ad8bc73ac09b14cb72059c9dca and had my first successful build of the second (yellow) column of build-images yesterday.  Today I create the respective Octave 4.0.0 to 6.2.0 images.  Stay tuned until later today and thanks for testing, using, and reporting :wink: 

I am interested in your GitLab pipeline, take a look at it later.

**Comment by siko1056** [comment]
Now all Octave 6 images are properly based on Ubuntu 20.04.

The next days I rebuild those images with `apt install --no-install-recommends`.  Especially updating to Ubuntu 20.04 really causes the resulting images to increase in size by 150% :fearful:  But this should not affect you using the current ones.

Closing report.  Please report here, if further issues occur.
