### ISSUE TITLE
dockerhub readme file missing newlines

### ISSUE THREAD

**Issue by cbm755** [gnu-octave/docker#10]
Go to [1] see this:

![image](https://user-images.githubusercontent.com/818622/181855623-28afec2a-ea97-450f-b45b-c2f5288bccd1.png)

**update** notice that the `# obtain image` is one big run-on line.  Not sure where that readme is sourced from...

[1] https://hub.docker.com/r/gnuoctave/octave

**Comment by siko1056** [comment]
Thanks for the pointer.  Others also complained why DockerHub needs those extra blank lines to create spaces... Let us add them as this project is targeted for this platform and it looks more serious.  Hopefully fixed with 4e2ddc257fb1ca2e9c0075a4ad9992300fda8dc9.
