### ISSUE TITLE
Should the latest image be tagged with the `latest` tag?

### ISSUE THREAD

**Issue by alexvong243f** [gnu-octave/docker#11]
According to https://www.howtogeek.com/devops/understanding-dockers-latest-tag/ `latest` is used as the default tag if no tag is provided. On the other hand, it won't be created automatically if a tag is provided.

I don't know docker well enough to know if it is the recommended practice to tag the latest image with the `latest` tag manually. WDYT?

See also the discussion in https://github.com/cbm755/octsympy/pull/1200

**Comment by siko1056** [comment]
Thanks for the report @alexvong1995 , I think it is possible to push a latest tag and will inform you here once it is available.

**Comment by siko1056** [comment]
@alexvong1995 let's give the GitHub Actions pipeline 3-4 hours and finally see if a latest tag has been pushed.
