### ISSUE TITLE
Bash install Octave package

### ISSUE THREAD

**Issue by jiedxu** [gnu-octave/docker#14]
Hello again. I have another question. Is there a way to install [Octave packages](https://gnu-octave.github.io/packages/) via bash? I'd like to include some packages in my custom docker image.

**Comment by siko1056** [comment]
Sure, you can just call Octave itself in a custom Dockerfile:
```Dockerfile
FROM gnuoctave/octave:7.2.0

RUN octave --no-history --eval \
      "pkg install -forge interval"
```

**Comment by jiedxu** [comment]
Perfect. Thank you very much.
