### ISSUE TITLE
[maint] protect the main branch

### ISSUE THREAD

**Issue by cbm755** [gnu-octave/docker#17]
Should this have a protected `main` branch?  I was able to push directly to `main` for c6ed029a921c6ebe853bf717aa03eb0888063cb3

That was a trivial fix so I'm unapologetic ;-) but maybe I shouldn't be allowed to do that at all?

**Comment by cbm755** [comment]
@siko1056 I went a head and turned that on.  No reviews required so we can still push easily but at least it should prevent accidents.

Undo that if you want, or close this issue if happy!

**Comment by cbm755** [comment]
It only sort of worked.  I was able to push 2de43de75f41b3a52a8186321cb4b5d171128100:
```
git push origin main
Enumerating objects: 5, done.
Counting objects: 100% (5/5), done.
Delta compression using up to 16 threads
Compressing objects: 100% (3/3), done.
Writing objects: 100% (3/3), 304 bytes | 304.00 KiB/s, done.
Total 3 (delta 2), reused 0 (delta 0), pack-reused 0
remote: Resolving deltas: 100% (2/2), completed with 2 local objects.
remote: Bypassed rule violations for refs/heads/main:
remote: 
remote: - Changes must be made through a pull request.
remote: 
To https://github.com/gnu-octave/docker.git
   c6ed029..2de43de  main -> main
```


Note "remote: Bypassed rule violations for refs/heads/main:".... maybe I didn't click all the correct checkboxes from the bazillion on offer...

**Comment by siko1056** [comment]
Hi @cbm755 ,
Thanks for the measures to protect the main branch.  I think it is a good idea and what you experienced is that there is a back door for org admins to bypass the restriction.  The only good thing is that admins must acknowledge that they bypass a rule... I think it is fair enough protection and I really do not mind other people to work on this repository :wink:
