### ISSUE TITLE
Build containers with RapidJSON

### ISSUE THREAD

**Issue by tiborauer** [gnu-octave/docker#19]
Would it be possible to build the containers with RapidJSON?

**Comment by siko1056** [comment]
Thanks for the pointer @tiborauer.  I think you refer to building Octave using RapidJSON?
```
>> jsondecode ('jsonfile.json')
error: jsondecode: support for JSON decoding through RapidJSON was unavailable or disabled when Octave was built
```

As RapidJSON is a header library, I can only install an ancient release from 2016 via the Ubuntu package manager https://packages.ubuntu.com/search?keywords=rapidjson-dev, but I assume installing RapidJSON header files is not what you are asking for?

**Comment by tiborauer** [comment]
As far as I understand only the header library may be only missing. Here is my take on building Octave:
https://github.com/reprostat/reproanalysis/blob/d9bfacbe0e1ab5856d99a50138ecd9bd0aebf49a/.circleci/config.yml#L155-L164, based on the [offical guideline](https://wiki.octave.org/Octave_for_Debian_systems#The_right_way).

**Comment by siko1056** [comment]
@tiborauer this issue should be fixed for the Octave versions that support `json{en/de}code` with the following fix:

https://github.com/gnu-octave/docker/commit/d8c92797afd9d5b51157ee8bdcace40fdcfdfda7#diff-abb6f2ef7075120846a258e74110c54d310deee5ac05501a0e51f381be9d3a54R260-R269

I am currently rebuilding the images until tomorrow.

**Comment by siko1056** [comment]
@tiborauer The issue should be fixed now for Octave 7.x to 8.x.  Due to other errors the build took longer than expected, but finally succeeded https://github.com/gnu-octave/docker/actions/runs/6962679183.

If issues with JSON remain, please feel free to reopen this issue.

**Comment by tiborauer** [comment]
Thank you, Kai!
