### ISSUE TITLE
QT graphics toolkit

### ISSUE THREAD

**Issue by tiborauer** [gnu-octave/docker#22]
Could you add QT to the build? I need `getframe` function which is supported only by the QT graphics toolkit.

**Comment by siko1056** [comment]
Basically the container image is build using QT.  How do you start the container?

https://github.com/gnu-octave/docker/blob/fa5448fd286c4b40b4dfd98a3cebbac83422c58b/install.sh#L213-L226

Eventually you must give the container access to your hosts `$DISPLAY` or `$XDG_RUNTIME_DIR` directory to function properly.  If you use the `install.sh` script, you should be able to run Octave as if installed natively on the system build with QT.

**Comment by tiborauer** [comment]
Thank you for the fast response!

I am running it in CI with DISPLAY environmental variable not set. Octave also disables the GUI features accordingly.

I have no issue, however, if I build Octave from source.

**Comment by siko1056** [comment]
If you build and run Octave from source on the host (CI) system all resources and environment variables QT needs are shared at runtime automatically.

However, if you run a container, you must expose those resources and environment variables yourself to the container.  Even if the `$DISPLAY` variable is empty, it must be set for example.  If you use and fill the parameters above, does it happen to work?

Otherwise was it possible share the used CI system and the way how you start the container image to provide any help despite wild guessing from my end?

**Comment by tiborauer** [comment]
Thank you!

I wonder whether https://github.com/gnu-octave/docker/blob/fa5448fd286c4b40b4dfd98a3cebbac83422c58b/install.sh#L216 should be `--env=\"DISPLAY=\$DISPLAY\" \\`.

I am using CircleCI and am unsure how to share the CI environment with you. I can certainly invite you to the GitHub project, which should allow you to monitor (and adjust) the CI runs.

**Comment by tiborauer** [comment]
I managed to figure out based on your hints.
Thanks!

**Comment by siko1056** [comment]
Thanks for the feedback.  I would be curious if the given arguments were enough or if further tweaks were necessary.

I will try the `--env=\"DISPLAY=\$DISPLAY\"`.  It makes lots of sense, but I forgot why I did this a year ago.

**Comment by tiborauer** [comment]
Here is my take: 
https://github.com/reprostat/reproanalysis/blob/73f2ad4eb28d05957582cc0eb9fdbf567c764f59/.circleci/config.yml#L59-L60

As you can see, no major tweak was necessary. I only added `--privileged` to allow installation of libraries required by the video package.

**Comment by tiborauer** [comment]
BTW, you do not need to modify the line with `DISPLAY`. Docker takes its value from the environment if no value is specified. Actually, you can further simplify the call by removing values for the HOME and the XDG_RUNTIME_DIR

**Comment by siko1056** [comment]
Thanks again for your reply @tiborauer I also learned something new :+1:
