### ISSUE TITLE
Add libraries to support packages

### ISSUE THREAD

**Issue by tiborauer** [gnu-octave/docker#24]
Can you please add libopencv-dev libavformat-dev libavcodec-dev libswscale-dev to support the video package?

I can install them only if I use the container as the default (root) user, but then I lose access to /run/user and, consequently, to some of the graphical capabilities.

**Comment by siko1056** [comment]
Hello @tiborauer ,

Thanks for the suggestion.  Installing these packages will add another 500 MB to the container images build here :scream: Those are for my taste already prohibitively large for a container images.
```
>> system ("sudo apt install --no-recommends libopencv-dev libavformat-dev libavcodec-dev libswscale-dev")
...
After this operation, 501 MB of additional disk space will be used.
```

As long as I maintain this repo mostly, I prefer not to add those packages.

However, I have absolutely no objections, if you fork this project (also within this organization on GitHub) and build customized container images for your purpose or build upon the ones build here.  They will be as easy to maintain as those images here.

---

Trying the non-forking approach.

It seems that in your container runtime environment you cannot become a user, right?  The way I use the container you are a normal user and can install packages in the "normal" way:
```
>> system ("id")
uid=1000(siko1056) gid=1000(siko1056) groups=1000(siko1056),27(sudo)
ans = 0
>> system ("sudo apt update")
>> system ("sudo apt install --no-recommends libopencv-dev libavformat-dev libavcodec-dev libswscale-dev")
...
After this operation, 501 MB of additional disk space will be used.
```
You inevitably have to be root user in your setup?

For example to make this container image desktop GUI usable, I inject in the container an entrypoint via Docker

https://github.com/gnu-octave/docker/blob/fa5448fd286c4b40b4dfd98a3cebbac83422c58b/install.sh#L223-L224

https://github.com/gnu-octave/docker/blob/fa5448fd286c4b40b4dfd98a3cebbac83422c58b/install.sh#L253-L266

Is this an option for your CI/CD system?

**Comment by tiborauer** [comment]
I said before, my CI is working as is. It is rather an issue whe using the container on cluster (apptainer/syngularity with non-suid instalation). 

I am afraid the "normal user" way does not work on a cluster. This is the error I receive if I use `sudo apt update`: `sudo: /etc/sudo.conf is owned by uid 1225052, should be 0`.

I understand that you do not want to extend the container, so I fork build custom image.

You can close this issue. Thank you!
