### ISSUE TITLE
 libQt5Core.so.5: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by majestichou** [gnu-octave/docker#25]
I run the following code
`docker run --rm --network=host --env="DISPLAY" --env="HOME=$HOME" --env="XDG_RUNTIME_DIR=$XDG_RUNTIME_DIR"  --user $(id -u):$(id -g)  --volume="$HOME:$HOME:rw" --volume="/dev:/dev:rw" --volume="/run/user:/run/user:rw" --workdir="$HOME" docker.io/gnuoctave/octave:8.4.0 octave --gui`
then i got the error:
`/usr/libexec/octave/8.4.0/exec/x86_64-pc-linux-gnu/octave-gui: error while loading shared libraries: libQt5Core.so.5: cannot open shared object file: No such file or directory`

**Comment by majestichou** [comment]
I run these code on Centos7

**Comment by siko1056** [comment]
Thanks for the last clarification.  I wrote about this issue in my blog, the default Linux Kernel of Centos 7 is too old for Qt.

https://siko1056.github.io/blog/2021/06/10/octave-docker.html (section: "Bad news for oldtimers (RHEL/CentOS 7)")

Please open the issue if there is anything else that can be done.
