### ISSUE TITLE
How to make qt available in cli mode

### ISSUE THREAD

**Issue by jgayer** [gnu-octave/docker#3]
Were moving from a 5.1.0 docker build from scratch to the official 6.3.0 docker image.

Before we could use qt graphics toolkit by calling octave --gui --no-gui, though we needed to restart the container once before qt was available in available_graphics_toolkits(). This hack does not seem to work in the official 6.3.0 image anymore.

Is there any other way to make qt available in a no-gui environment?
I've tried all combinations of octave, --no-gui, -gui, octavel-cli etc. and cannot find official information if that is even supposed supported. 

In this Bugreport [bug #54954: available_graphics_toolkit should not include 'qt' with octave-cli or --no-gui-libs](https://savannah.gnu.org/bugs/?func=detailitem&item_id=54954) the author talks about qt being "dynamically loaded", which could explain our hack to use it after a restart a bit.

I understand that this is not strictly a docker issue, but since docker images are often used in a headless microservice environment I think it is related. 

Thanks!

**Comment by siko1056** [comment]
Thanks for the challenge @jgayer. I [updated the Octave Docker images](2f533870026112eef9801942eab6847c04593542) using [`xvfb-run`](https://packages.ubuntu.com/en/focal/xvfb) and hopfully you can archive your goals with

```
docker run --init -it gnuoctave/octave:6.4.0 xvfb-run octave -q --eval available_graphics_toolkits --persist

Executing the command: xvfb-run octave -q --eval available_graphics_toolkits --persist
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-jovyan'
ans =
{
  [1,1] = fltk
  [1,2] = gnuplot
  [1,3] = qt
}
```

**Comment by jgayer** [comment]
This does indeed work, but I hope that octave offers a native solution in the future.

I did not know about Xvfb.
Thanks so much!

**Comment by siko1056** [comment]
Thanks for reporting back and that the solution works for you :slightly_smiling_face: 

I fowarded your question to the Octave Discourse forum, as I do not know a good answer myself:

https://octave.discourse.group/t/why-does-the-octave-qt-graphics-toolkit-need-a-display/1761
