### ISSUE TITLE
trouble building working IPOPT Mex file

### ISSUE THREAD

**Issue by rdzman** [gnu-octave/docker#5]
I'm trying to build a working [IPOPT](https://github.com/coin-or/Ipopt/) MEX file for Octave-6.4 using `gnuoctave/octave:6.4.0`. But I'm getting consistent segmentation faults when I call the MEX function (except with arguments defining an essentially empty problem).

This is after doing ...
```
RUN apt-get --yes update  && \
    DEBIAN_FRONTEND="noninteractive" \
    apt-get --no-install-recommends --yes install \
        liblapack-dev \
        coinor-libipopt-dev \
        pkg-config
```

I'm wondering if it is an incompatibility between the LAPACK used for the IPOPT libs and for Octave? And if so, where would I find the LAPACK libs used to build Octave?

**Comment by rdzman** [comment]
I'm still stuck. I thought I'd try to build IPOPT from scratch, like I do on the macOS runners for GitHub actions. I am able to build IPOPT just fine with ...

```
git clone https://github.com/coin-or/coinbrew
cd coinbrew
export with_lapack_lflags="-lopenblas"
./coinbrew fetch Ipopt --no-prompt
./coinbrew build Ipopt --prefix /usr --tests none --no-prompt
```

But if I use `--tests all` they all fail with segmentation faults.

It looks like the verbose output of the Java based test has the most info ...
```
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007fa5f7089d87, pid=22130, tid=22131
#
# JRE version: OpenJDK Runtime Environment (11.0.11+9) (build 11.0.11+9-Ubuntu-0ubuntu2.20.04)
# Java VM: OpenJDK 64-Bit Server VM (11.0.11+9-Ubuntu-0ubuntu2.20.04, mixed mode, sharing, tiered, compressed oops, g1 gc, linux-amd64)
# Problematic frame:
# C  [libopenblas.so.0+0x179dd87]  dcopy_k_HASWELL+0x387
```

And another test says ...
```
Program received signal SIGSEGV: Segmentation fault - invalid memory reference.

Backtrace for this error:
#0  0x7f04294c2d5a
#1  0x7f04294c1ef5
#2  0x7f04292f620f
#3  0x7f04280cbd87
```

I can even successfully build the MEX interface against these libraries, but it also results in a seg fault when called from Octave.

FWIW, I am able to build and use the IPOPT MEX file just fine on the Linux runners for GitHub actions (using `apt-get` to install Octave and the IPOPT libraries). 

Is there something about the build environment you use on these images that is different from the Ubuntu distribution that might cause problems with the MUMPS solver or something?

Any suggestions would be greatly appreciated.

I started a related Ipopt thread [here](https://github.com/coin-or/Ipopt/discussions/544), in case someone there has some ideas.

**Comment by siko1056** [comment]
Thank you for using the Docker images.  Probably it is better to get this problem settled first here in this issue tracker, as the maintainers of https://github.com/coin-or/Ipopt/discussions/544 do not know about the non-standard configuration of the Docker images (and probably do not want to know about any "exotic" configuration either :slightly_smiling_face: ).

First of all, the provided Docker images use a self-compiled OpenBLAS and SuiteSparse version

https://github.com/gnu-octave/docker/blob/dd3d3b6f4b9202423275424ecb77c7b3bb57f7ed/build-octave-6.docker#L106-L149

to enable [ilp64](https://en.wikipedia.org/wiki/64-bit_computing#64-bit_data_models) especially for Fortran integers.  Thus whatever you install from the official Ubuntu repositories requiring "blas" packages is very likely to fail :sweat: 

Therefore, the self-compiled approach seems to be leading into the right direction :+1:

The documentation of IPOPT https://coin-or.github.io/Ipopt/INSTALL.html is excellent (compared to many other FLOSS projects I merged into this Docker project).  Below I followed their steps (adapting to ilp64) from inside the Octave Docker image "command window" and got things to work:

```
system ("git clone --depth=1 https://github.com/coin-or-tools/ThirdParty-ASL.git")
cd ThirdParty-ASL
system ("./get.ASL")
system ("./configure --with-intsize=64")
system ("make -j8")
system ("sudo make install")


system ("git clone --depth=1 https://github.com/coin-or-tools/ThirdParty-HSL.git")
cd ThirdParty-HSL
system ("./configure")
system ("make -j8")
system ("sudo make install")


system ("git clone --depth=1 https://github.com/coin-or-tools/ThirdParty-Mumps.git")
cd ThirdParty-Mumps
system ("./get.Mumps")
system ("./configure --with-intsize=64 --with-lapack-lflags=-lopenblas --with-metis-cflags=-I/usr/include/suitesparse")
system ("make -j8")
system ("sudo make install")

 
system ("git clone --depth=1 https://github.com/coin-or/Ipopt.git")
cd Ipopt
system ("./configure --with-intsize=64 --with-lapack-lflags=-lopenblas --disable-java")
system ("make -j8")
system ("make test")
system ("sudo make install")
```

Output of `make test`:

```
Running unitTests...

Testing AMPL Solver Executable...
    Test passed!
Testing C++ Example...
    Test passed!
Testing C Example...
    Test passed!
Testing Fortran Example...
    Test passed!
Skip testing Java Example (Java interface not build)
Testing sIpopt Example parametric_cpp...
    Test passed!
Testing sIpopt Example redhess_cpp...
    Test passed!
Testing EmptyNLP Example...
    Test passed!
Testing GetCurr Example...
    Test passed!
```

Two final notes:
- Everytime you run the Octave Docker images, you have to install the software again.  Consider storing the built libraries in your user's home directory using the `--prefix=/home/username/lib` for the configuration.
- The Java interface does not work.  Unless it is of any importance, I do not feel eager to investigate the problem :innocent: .

**Comment by rdzman** [comment]
Thanks, @siko1056 and @svigerske, I didn't notice the 64-bit integer build. That was exactly the piece I needed. And sorry again about the cross-post and duplicate effort ... wasn't sure who would be most equipped to spot the issue.

I now have a working IPOPT build, but the issue is still causing an error when I try to build the MEX interface. Forgive my ignorance about how integer sizes work with compilers (been years since I did any real work in compiled languages) ... but is there a flag I can pass to the compiler to switch to a 64-bit int MEX file?

In case it helps, I'm building using the MatlabInterface files from [IPOPT 3.11.9](https://github.com/coin-or/Ipopt/archive/releases/3.11.9.tar.gz), and [this Makefile](https://github.com/MATPOWER/action-install-ipopt-octave/blob/main/ipopt/Makefile), with the following lines.
```
CXXFLAGS = -fPIC -std=c++11 -O3 -DIPOPT_BUILD -DMATLAB_MEXFILE -DHAVE_CSTDDEF

INCL = `pkg-config --cflags ipopt` -I`mkoctfile -p OCTINCLUDEDIR`
LIBS = `pkg-config --libs ipopt`

all: ipopt.mex

%.o: %.cpp
	g++ $(CXXFLAGS) $(INCL) -o $@ -c $^

ipopt.mex: $(OBJS)
	mkoctfile $(LIBS) -v --mex --output $@ $^
```
FWIW, this Makefile works just fine when building against the IPOPT and Octave installed by `apt-get`.

Thanks again for any additional pointers.

And, btw, @siko1056, thanks for the `--prefix=/home/username/lib` suggestion, but I probably won't need it as I'm building my own Docker image, based on yours, with the IPOPT interface, some other solvers, and my own package ([MATPOWER](https://matpower.org)) pre-installed, so everything should be there when somebody runs it. And, fortunately, I don't need Java either.

**Comment by rdzman** [comment]
The error I'm getting now is ...
```
g++ -fPIC -std=c++11 -O3 -DIPOPT_BUILD -DMATLAB_MEXFILE -DHAVE_CSTDDEF `pkg-config --cflags ipopt` -I`mkoctfile -p OCTINCLUDEDIR` -o callbackfunctions.o -c callbackfunctions.cpp
g++ -fPIC -std=c++11 -O3 -DIPOPT_BUILD -DMATLAB_MEXFILE -DHAVE_CSTDDEF `pkg-config --cflags ipopt` -I`mkoctfile -p OCTINCLUDEDIR` -o ipoptoptions.o -c ipoptoptions.cpp
ipoptoptions.cpp: In member function ‘int IpoptOptions::printLevel() const’:
ipoptoptions.cpp:72:48: error: cannot bind non-const lvalue reference of type ‘Ipopt::Index&’ {aka ‘long int&’} to an rvalue of type ‘Ipopt::Index’ {aka ‘long int’}
   72 |   app.Options()->GetIntegerValue("print_level",value,"");
      |                                                ^~~~~
In file included from /usr/include/coin-or/IpNLP.hpp:15,
                 from /usr/include/coin-or/IpIpoptApplication.hpp:14,
                 from ipoptoptions.hpp:13,
                 from ipoptoptions.cpp:9:
/usr/include/coin-or/IpOptionsList.hpp:318:26: note:   initializing argument 2 of ‘virtual bool Ipopt::OptionsList::GetIntegerValue(const string&, Ipopt::Index&, const string&) const’
  318 |       Index&             value,
      |       ~~~~~~~~~~~~~~~~~~~^~~~~
```

**Comment by svigerske** [comment]
So the problem is in [this code](https://github.com/coin-or/Ipopt/blob/1183137bbc745b29f9ea50df83b2f3a3f82a85e7/Ipopt/contrib/MatlabInterface/src/ipoptoptions.cpp#L70-L74):
```cpp
int IpoptOptions::printLevel() const {
  int value;  // The return value.
  app.Options()->GetIntegerValue("print_level",value,"");
  return value;
}
```
`value` should be of type `Ipopt::Index` instead of `int`.

**Comment by siko1056** [comment]
@rdzman MATPOWER looks great :+1:  And I am happy you take the effot to use the Octave Docker images.  With the fix suggested by @svigerske can you compile the mex file?

@svigerske will this be fixed upstream?

**Comment by svigerske** [comment]
> @svigerske will this be fixed upstream?

I don't think so. Ipopt 3.11.9 is from 2014, but we are now at 3.14.4.   
Two years ago (Ipopt 3.13), the Matlab interface was removed from Ipopt, because users reported that it didn't work anymore and no one stepped up to reply to these reports or to maintain the interface. Further, someone had developed an interface in a separate project: https://github.com/ebertolazzi/mexIPOPT

**Comment by rdzman** [comment]
> @rdzman MATPOWER looks great 👍 And I am happy you take the effot to use the Octave Docker images. With the fix suggested by @svigerske can you compile the mex file?

@siko1056 Thanks for the kind words about MATPOWER. While Stefan's fix does get that particular file to compile, it now fails elsewhere (see below).

@svigerske Thanks for the tip. Unfortunately, it seems mexIPOPT does not yet work out-of-the-box on Octave either (see ebertolazzi/mexIPOPT#13), but I suppose it might make sense to invest my effort there rather than fix the old, abandoned code from 3.11.9. I suppose I should at least give [this patch](https://github.com/ebertolazzi/mexIPOPT/issues/13#issue-991984723) a try.

Having said that however, in case it's a simple fix for a C++ programmer (which I am not), here is the current error ...
```
g++ -fPIC -std=c++11 -O3 -DIPOPT_BUILD -DMATLAB_MEXFILE -DHAVE_CSTDDEF `pkg-config --cflags ipopt` -I`mkoctfile -p OCTINCLUDEDIR` -o ipopt.o -c ipopt.cpp
ipopt.cpp: In function ‘void mexFunction(int, mxArray**, int, const mxArray**)’:
ipopt.cpp:106:50: error: invalid new-expression of abstract class type ‘MatlabProgram’
  106 |       = new MatlabProgram(x0,funcs,options,x,info);
      |                                                  ^
In file included from ipopt.cpp:16:
matlabprogram.hpp:26:7: note:   because the following virtual functions are pure within ‘MatlabProgram’:
   26 | class MatlabProgram : public TNLP {
      |       ^~~~~~~~~~~~~
In file included from /usr/include/coin-or/IpIpoptApplication.hpp:13,
                 from ipoptoptions.hpp:13,
                 from options.hpp:14,
                 from ipopt.cpp:11:
/usr/include/coin-or/IpTNLP.hpp:99:17: note: 	‘virtual bool Ipopt::TNLP::get_nlp_info(Ipopt::Index&, Ipopt::Index&, Ipopt::Index&, Ipopt::Index&, Ipopt::TNLP::IndexStyleEnum&)’
   99 |    virtual bool get_nlp_info(
      |                 ^~~~~~~~~~~~
/usr/include/coin-or/IpTNLP.hpp:170:17: note: 	‘virtual bool Ipopt::TNLP::get_bounds_info(Ipopt::Index, Ipopt::Number*, Ipopt::Number*, Ipopt::Index, Ipopt::Number*, Ipopt::Number*)’
  170 |    virtual bool get_bounds_info(
      |                 ^~~~~~~~~~~~~~~
/usr/include/coin-or/IpTNLP.hpp:301:17: note: 	‘virtual bool Ipopt::TNLP::get_starting_point(Ipopt::Index, bool, Ipopt::Number*, bool, Ipopt::Number*, Ipopt::Number*, Ipopt::Index, bool, Ipopt::Number*)’
  301 |    virtual bool get_starting_point(
      |                 ^~~~~~~~~~~~~~~~~~
/usr/include/coin-or/IpTNLP.hpp:343:17: note: 	‘virtual bool Ipopt::TNLP::eval_f(Ipopt::Index, const Number*, bool, Ipopt::Number&)’
  343 |    virtual bool eval_f(
      |                 ^~~~~~
/usr/include/coin-or/IpTNLP.hpp:363:17: note: 	‘virtual bool Ipopt::TNLP::eval_grad_f(Ipopt::Index, const Number*, bool, Ipopt::Number*)’
  363 |    virtual bool eval_grad_f(
      |                 ^~~~~~~~~~~
/usr/include/coin-or/IpTNLP.hpp:382:17: note: 	‘virtual bool Ipopt::TNLP::eval_g(Ipopt::Index, const Number*, bool, Ipopt::Index, Ipopt::Number*)’
  382 |    virtual bool eval_g(
      |                 ^~~~~~
/usr/include/coin-or/IpTNLP.hpp:421:17: note: 	‘virtual bool Ipopt::TNLP::eval_jac_g(Ipopt::Index, const Number*, bool, Ipopt::Index, Ipopt::Index, Ipopt::Index*, Ipopt::Index*, Ipopt::Number*)’
  421 |    virtual bool eval_jac_g(
      |                 ^~~~~~~~~~
/usr/include/coin-or/IpTNLP.hpp:588:17: note: 	‘virtual void Ipopt::TNLP::finalize_solution(Ipopt::SolverReturn, Ipopt::Index, const Number*, const Number*, const Number*, Ipopt::Index, const Number*, const Number*, Ipopt::Number, const Ipopt::IpoptData*, Ipopt::IpoptCalculatedQuantities*)’
  588 |    virtual void finalize_solution(
      |                 ^~~~~~~~~~~~~~~~~
ipopt.cpp:119:34: error: cannot bind non-const lvalue reference of type ‘Ipopt::Index&’ {aka ‘long int&’} to an rvalue of type ‘Ipopt::Index’ {aka ‘long int’}
  119 |       stats->NumberOfEvaluations(obj,con,grad,jac,hess);
      |                                  ^~~
In file included from ipopt.cpp:20:
/usr/include/coin-or/IpSolveStatistics.hpp:76:14: note:   initializing argument 1 of ‘virtual void Ipopt::SolveStatistics::NumberOfEvaluations(Ipopt::Index&, Ipopt::Index&, Ipopt::Index&, Ipopt::Index&, Ipopt::Index&) const’
   76 |       Index& num_obj_evals,
      |       ~~~~~~~^~~~~~~~~~~~~
make: *** [Makefile:23: ipopt.o] Error 1
```

**Comment by svigerske** [comment]
Yes, patching up ebertolazzi/mexIPOPT would be the way to go.

The other compilation errors are probably due to more uses of `int` where `Index` should have been used. That only works fine if `Index` equals `int`, which it isn't in this build.

**Comment by rdzman** [comment]
Fortunately, it wasn't too much work. See ebertolazzi/mexIPOPT#14.

Thanks to input from both of you, I now have a Docker image with Octave and a working pre-installed IPOPT MEX interface!
